# Generated by Django 5.2.8 on 2025-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0002_reservation_email_alter_reservation_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
